/** Shared SEO keyword pools for Quizzical.site */

/** Brand and creator keywords — included on every indexed page. */
export const BRAND_KEYWORDS = [
  "Sonke AI",
  "SonkeAI",
  "Zama Shange",
  "Burdolar",
  "BDL Corp",
  "BDL Corporation",
  "Quizzical by BDL Corp",
  "Quizzical BDL Corp",
  "Sonke AI quiz",
  "Zama Shange quiz",
  "Burdolar games",
  "BDL Corp games",
  "South African quiz games",
  "African quiz platform",
];

export const BASE_KEYWORDS = [
  ...BRAND_KEYWORDS,
  "quizzical",
  "quizzical.site",
  "quizzical quiz",
  "quizzical games",
  "quizzical trivia",
  "quizzical online",
  "free online quiz",
  "free quiz games",
  "free trivia games",
  "online trivia",
  "online trivia games",
  "trivia game",
  "trivia quiz online",
  "quiz game online",
  "play quiz free",
  "play trivia free",
  "no download quiz",
  "browser quiz game",
  "web quiz game",
  "educational quiz",
  "educational trivia",
  "interactive quiz",
  "interactive trivia game",
  "learn while playing",
  "learn after answer",
  "multiple choice quiz",
  "multiple choice trivia",
  "timed quiz game",
  "timed trivia challenge",
  "solo quiz game",
  "single player quiz",
  "quiz for adults",
  "quiz for students",
  "quiz for kids",
  "quiz for teens",
  "fun trivia online",
  "fun quiz website",
  "brain game",
  "brain teaser quiz",
  "knowledge quiz",
  "general knowledge test",
  "IQ quiz fun",
  "daily trivia",
  "quick quiz game",
  "short quiz online",
  "quiz challenge",
  "trivia challenge",
  "score quiz game",
  "high score quiz",
  "quiz with timer",
  "quiz with facts",
  "reveal card quiz",
  "picture quiz online",
  "image quiz game",
  "photo quiz free",
  "guess the picture quiz",
  "visual trivia",
  "flag quiz online",
  "country flag quiz",
  "world flags quiz",
  "guess the flag game",
  "geography quiz free",
  "movie quiz online",
  "sports quiz free",
  "celebrity quiz game",
  "music quiz online",
  "history trivia free",
  "science quiz online",
  "AI quiz generator free",
  "AI trivia generator",
  "custom quiz maker",
  "create quiz online",
  "random quiz generator",
  "surprise me quiz",
  "best free quiz site",
  "best trivia website",
  "top quiz games 2026",
  "play quiz now",
  "instant quiz game",
  "mobile quiz game",
  "phone quiz app web",
  "tablet quiz game",
  "family quiz night online",
  "party trivia game",
  "pub quiz online free",
  "virtual trivia night",
  "classroom quiz game",
  "teacher quiz resource",
  "student trivia game",
  "homework quiz fun",
  "study quiz game",
  "revision quiz online",
  "exam prep trivia",
  "world capitals quiz",
  "capital cities game",
  "country quiz game",
  "map quiz online",
  "landmarks quiz",
  "travel trivia quiz",
  "culture quiz online",
  "pop culture trivia",
  "entertainment trivia",
  "Hollywood quiz free",
  "Netflix movie quiz",
  "football quiz online",
  "soccer trivia game",
  "NBA quiz free",
  "Olympics trivia",
  "animal quiz online",
  "nature trivia game",
  "space quiz free",
  "planet quiz game",
  "book quiz online",
  "author trivia game",
  "literature quiz free",
  "language quiz online",
  "vocabulary quiz game",
  "word quiz free",
  "easy quiz online",
  "hard trivia questions",
  "medium difficulty quiz",
  "beginner trivia",
  "expert quiz challenge",
];

export const PAGE_KEYWORDS = {
  home: [
    ...BRAND_KEYWORDS,
    "best free quiz site",
    "online quiz platform",
    "picture quiz games",
    "flag quiz",
    "celebrity quiz",
    "movie trivia",
    "sports quiz",
    "geography trivia",
    "AI quiz",
    "random quiz generator",
    "play free quizzes online",
    "quizzical homepage",
    "free quiz hub",
    "trivia hub online",
    "quiz collection free",
    "all categories quiz",
    "world quiz games",
    "guess games online",
    "learning games free",
    "smart games online",
    "quiz site no signup",
    "free account quiz tracking",
    "sign in quiz scores",
  ],
  ai: [
    ...BRAND_KEYWORDS,
    "AI quiz generator",
    "AI trivia maker",
    "create quiz with AI",
    "custom quiz generator",
    "generate quiz online free",
    "AI quiz maker",
    "topic quiz generator",
    "ChatGPT quiz",
    "automatic quiz creator",
    "make your own quiz",
    "Sonke AI quiz generator",
    "AI powered trivia",
    "machine learning quiz",
    "GPT quiz creator",
    "prompt to quiz",
    "any topic quiz AI",
    "instant AI quiz",
    "AI question generator",
    "AI multiple choice",
    "smart quiz builder",
  ],
  signin: [
    ...BRAND_KEYWORDS,
    "quizzical login",
    "quizzical sign in",
    "quiz account login",
    "save quiz scores",
    "track trivia progress",
    "quiz player account",
  ],
  signup: [
    ...BRAND_KEYWORDS,
    "quizzical sign up",
    "quizzical register",
    "create quiz account",
    "free quiz account",
    "join quizzical",
    "quiz player signup",
  ],
  about: [
    ...BRAND_KEYWORDS,
    "about quizzical",
    "AI quiz platform",
    "learn while playing",
    "educational quiz games",
    "BDL Corp about",
    "free trivia platform",
  ],
  founder: [
    ...BRAND_KEYWORDS,
    "Zama Shange founder",
    "Zama Shange developer",
    "BDL Corp founder",
    "South African developer",
    "Burdolar creator",
    "Sonke AI creator",
  ],
  privacy: [
    ...BRAND_KEYWORDS,
    "quizzical privacy policy",
    "quiz platform privacy",
    "data protection",
    "cookie policy",
  ],
  contact: [
    ...BRAND_KEYWORDS,
    "contact quizzical",
    "quiz support",
    "feedback quizzical",
    "BDL Corp contact",
  ],
  status: [
    ...BRAND_KEYWORDS,
    "quizzical status",
    "platform status",
    "service health",
    "quiz site uptime",
  ],
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  geography: [
    ...BRAND_KEYWORDS,
    "geography quiz",
    "world geography trivia",
    "capital cities quiz",
    "flags of the world",
    "country quiz",
    "map quiz",
    "guess the country",
    "landmarks quiz",
    "world capitals game",
    "flag guessing game",
    "continent quiz",
    "African geography quiz",
    "European capitals quiz",
    "Asian countries quiz",
    "Americas geography trivia",
    "oceania quiz",
    "UN countries quiz",
    "sovereign states quiz",
    "border countries quiz",
    "famous landmarks quiz",
    "natural wonders quiz",
    "rivers and mountains quiz",
    "world map trivia",
  ],
  history: [
    ...BRAND_KEYWORDS,
    "history quiz",
    "world history trivia",
    "WWII quiz",
    "historical trivia",
    "presidents quiz",
    "ancient history quiz",
    "medieval history quiz",
    "cold war trivia",
    "ancient Egypt quiz",
    "Roman empire quiz",
    "world war one quiz",
    "civil rights history quiz",
    "revolution history trivia",
    "monarchy history quiz",
    "historical figures quiz",
  ],
  "science-and-nature": [
    ...BRAND_KEYWORDS,
    "science quiz",
    "nature quiz",
    "space quiz",
    "solar system quiz",
    "biology quiz",
    "animal quiz",
    "science trivia online",
    "physics quiz free",
    "chemistry trivia",
    "human body quiz",
    "dinosaur quiz",
    "wildlife trivia",
    "environment quiz",
    "climate science quiz",
    "astronomy quiz online",
    "NASA space trivia",
    "planet names quiz",
    "invention quiz",
    "scientist quiz",
  ],
  sports: [
    ...BRAND_KEYWORDS,
    "sports quiz",
    "sports trivia",
    "football quiz",
    "guess the footballer",
    "athlete quiz",
    "Olympics quiz",
    "sports legends trivia",
    "Premier League quiz",
    "Champions League trivia",
    "World Cup quiz",
    "cricket quiz online",
    "rugby trivia",
    "tennis quiz free",
    "Formula 1 quiz",
    "boxing trivia game",
    "MMA quiz online",
    "golf quiz trivia",
    "NBA legends quiz",
    "NFL trivia game",
  ],
  entertainment: [
    ...BRAND_KEYWORDS,
    "movie quiz",
    "film trivia",
    "entertainment quiz",
    "guess the movie",
    "Hollywood quiz",
    "pop culture quiz",
    "TV show quiz",
    "sitcom trivia",
    "Oscars quiz",
    "Disney movie quiz",
    "Marvel quiz online",
    "superhero trivia",
    "actor quiz game",
    "actress picture quiz",
    "streaming movie quiz",
    "classic films trivia",
    "box office quiz",
    "director quiz game",
  ],
  "art-and-literature": [
    ...BRAND_KEYWORDS,
    "literature quiz",
    "book quiz",
    "author quiz",
    "art quiz",
    "classic novels quiz",
    "famous painters quiz",
    "Shakespeare quiz",
    "poetry trivia",
    "modern literature quiz",
    "Nobel prize literature",
    "museum art quiz",
    "Renaissance art trivia",
    "sculpture quiz",
    "architecture quiz",
    "famous books quiz",
  ],
  languages: [
    ...BRAND_KEYWORDS,
    "language quiz",
    "words quiz",
    "alphabet quiz",
    "vocabulary trivia",
    "world languages quiz",
    "Spanish quiz online",
    "French vocabulary quiz",
    "German language quiz",
    "Japanese quiz beginner",
    "Mandarin trivia",
    "translation quiz",
    "etymology quiz",
    "spelling bee online",
    "grammar quiz game",
  ],
  trivia: [
    ...BRAND_KEYWORDS,
    "general knowledge quiz",
    "random trivia",
    "fun facts quiz",
    "pub quiz online",
    "general trivia questions",
    "useless facts quiz",
    "did you know trivia",
    "mixed trivia quiz",
    "jack of all trades quiz",
    "quick fire trivia",
    "true or false quiz",
    "odd one out quiz",
    "this or that trivia",
    "daily general knowledge",
  ],
};

export const IMAGE_GAME_KEYWORDS: Record<string, string[]> = {
  celebrity: [
    ...BRAND_KEYWORDS,
    "guess the celebrity",
    "celebrity picture quiz",
    "who is this celebrity",
    "famous people quiz",
    "celebrity photo game",
    "star quiz",
    "Hollywood star quiz",
    "influencer quiz game",
    "red carpet quiz",
    "celebrity face game",
    "famous actor quiz",
    "pop star picture quiz",
  ],
  athlete: [
    ...BRAND_KEYWORDS,
    "guess the athlete",
    "tennis player picture quiz",
    "Olympic athlete quiz",
    "F1 driver quiz",
    "swimming star quiz",
    "gymnastics athlete quiz",
    "golf player quiz",
    "individual sports quiz",
    "niche sports picture quiz",
  ],
  football: [
    ...BRAND_KEYWORDS,
    "guess the footballer",
    "soccer player quiz",
    "football picture quiz",
    "Premier League player quiz",
    "World Cup player quiz",
    "Messi Ronaldo quiz",
    "football star photo game",
    "soccer trivia picture",
  ],
  basketball: [
    ...BRAND_KEYWORDS,
    "guess the basketball player",
    "NBA player quiz",
    "basketball picture quiz",
    "NBA star photo game",
    "LeBron Jordan quiz",
    "basketball trivia picture",
    "WNBA player quiz",
  ],
  cricket: [
    ...BRAND_KEYWORDS,
    "guess the cricketer",
    "cricket player quiz",
    "IPL player picture quiz",
    "Test cricket star quiz",
    "cricket photo game",
    "Virat Kohli quiz",
    "cricket trivia picture",
  ],
  movie: [
    ...BRAND_KEYWORDS,
    "guess the movie",
    "movie poster quiz",
    "film picture quiz",
    "movie scene quiz",
    "cinema trivia game",
    "blockbuster movie quiz",
    "film still quiz",
    "movie screenshot game",
    "classic movie poster quiz",
    "TMDB movie quiz",
  ],
  music: [
    ...BRAND_KEYWORDS,
    "guess the singer",
    "music artist quiz",
    "band picture quiz",
    "pop star quiz",
    "music trivia game",
    "rapper picture quiz",
    "rock band quiz",
    "album cover quiz",
    "music icon trivia",
    "Grammy artist quiz",
  ],
};

/** Long-tail keywords appended to quiz detail pages. */
export const QUIZ_LONGTAIL_KEYWORDS = [
  ...BRAND_KEYWORDS,
  "play free online",
  "no registration quiz",
  "instant play quiz",
  "learn fun facts",
  "educational reveal",
  "score tracking quiz",
  "timed round quiz",
  "10 question quiz",
  "multiple choice answers",
  "wrong answer learning",
  "quiz with explanations",
  "mobile friendly quiz",
  "share quiz score",
  "replay quiz game",
  "new questions each time",
];
